name: first workflow
on:  workflow_dispatch
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: print greetings
          run: echo "hello world"
        - name: good bye
          run: echo "Good bye- done"
   

